INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, ' Vida e a História de Madam C.J. Walker', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/2TMkFGAbsTfN3DHJu5AemEpdcEE.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3, 'Anne with an ‘E’', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/xWdSSB1La6FcXZUuuwvcqvB6Kdf.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Good Girls', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/d6gA2IHRLqtHcmSqkk91Xw0wtEv.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vis a Vis', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/vIFsPAn5EFHZnimvekXhi4LJf1p.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Anne Frank, Minha Melhor Amiga', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/4LEIoUuHQw1UhyyV8TCLNtO3E6g.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Incrível História de Adaline', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/gU84OUm9c4R44Zx8U1YPbCzKqIo.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Frida', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/a4hgR6aKoohB6MHni171jbi9BkU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Hora Mais Escura', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fWpjkM77R5o4MV0nxO2cnywkCoJ.jpg);
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mulher-Maravilha', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ujQthWB6c0ojlARk28NSTmqidbF.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Incrível Jessica James', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/zVWBQx6tsYmVDW9OWI6XIIYh611.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Malala', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lOYrqRKhOrPd5RvWoyTw71KVI6z.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Orange Is the New Black', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/enI85hAm51txs8jUY7PWQXR1Xm5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Mulheres do Século 20', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/txzTwljLAT5zAm4qzboV7O0TDPR.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Histórias Cruzadas', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/7iWfEm9VOeX8AAnC7F1ApxRDTfw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Grace and Frankie', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/3aD3PaSeF8eHJFLliLlWYw4EcPt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Tempo Entre Costuras', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/rVlgqzzOcThjVmMHs3bGpXfzC7v.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Crown', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/ehUMAA3qDR5HNor9DB60g72KNQZ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Como Defender um Assassino', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/sohKB3pnzq6iWOgLVxk8mpCFgTO.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Orphan Black', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/yET48smELUDAszOhHbL9A8RF3N8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Jane a Virgem ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/lBfJhjwcy7uX2MKLV7qbwXbQOzI.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Imperdoável', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/kbHo7UFYihixl5goN2Ro5Zs15Cw.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'As Telefonistas', ' https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9QMun5PmrdUISgk7RhhGi66E9Tg.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Chame a Parteira', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/b1p0nL00x563ACkcmGNIRP4ZnkA.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'GLOWt', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/aqQlgRgUwVTfbdxe33vfDEMiCa2.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Agent Carter', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/fpeMeA3b54TuPVSsnk03ZxlYCDF.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Tempos de Guerra ', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hxRnwBGuaWPXe6UTx2McQQ3ILeF.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Gambito da Rainha', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/hnGdmwFTkz4u5ojbX12orJM2aXl.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Old Guard', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/knfExByNW2jCwtmIuwYYxzPKpkm.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Lugar de Mulher', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/9VUh1tbBubznBdjV5OomzupyCgL.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Anatomia de Grey', 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/tWtGNTJUAuiM2O9wv0jejw45Sji.jpg');


INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);